title: "Shai S. Sabaroche - Mechanical Engineer"
description: "Portfolio showcasing research in biomechanical modeling, robotics, fracture mechanics, and autonomous systems."
theme: jekyll-theme-minimal
url: "https://shaisabaroche/shai-sabaroche.github.io"
markdown: kramdown
baseurl: ""
paginate: 5
author: "Shai S. Sabaroche"
exclude:
  - README.md
  - LICENSE
  - .gitignore
